version: '3'


services:
  postgres:
    image: postgres:latest
    container_name: GB_spring_auth
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5436:5432"

