spring:
  flyway:
#    откуда брать файл для бд
    locations: classpath:/db/forTestData
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabaseTest;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
